== WIGOS Metadata Representation (Version 2)

WIGOS Metadata Representation (WMDR) is an extension of the OGC API – Records standard and shall be encoded in GeoJSON. The normative provisions in WMDR (version 2) are denoted by the base URI (``http://wigos.wmo.int/spec/wmdr/2``) and requirements are denoted by partial URIs relative to this base. Property names, values and examples are represented with ``shaded text`` in this document.

//:sectnums!:
=== Requirements Class "Core"

include::../requirements/requirements_class_core.adoc[]

==== Overview

The table below provides an overview of the set of properties that may be included in a WMDR.

.Table. WMDR core properties
|===
|Property|Requirement|Description

|``id``
|**Required**
|A unique identifier of the station/platform (see TODO)

|``type``
|**Required**
|A fixed value denoting the WMDR as a GeoJSON ``Feature`` (see TODO)

|``conformsTo``
|**Required**
|The version of WMDR associated to which the record conforms (see TODO)

|``geometry``
|**Required**
|Geospatial location associated with the dataset, in a geographic coordinate reference system (see TODO)

|``properties.type``
|**Required**
|Record type (fixed to ``facility``)

|``properties.externalIds``
|Optional
|Persistent identifiers or handles for the dataset (see TODO)

|``properties.created``
|**Required**
|The date that the WMDR was created (see TODO)

|``properties.updated``
|Optional
|The date that the WMDR was updated (see TODO)

|``properties.contacts``
|**Required**
|Contact information for the dataset (see TODO)

|===

==== WIGOS Metadata Representation representation

A WMDR can be represented in various ways internally, in WIGOS systems and software tools, but its external representation is GeoJSON.

include::../recommendations/core/REC_media_type.adoc[]

==== Validation

The WMDR schema is based on the Requirements Class "Record Core" of OGC API – Records – Part 1: Core schema and the associated information model. WMDRs compliant with the WMDR schema are therefore compliant with the OGC API – Records record schema.

include::../requirements/core/REQ_validation.adoc[]

==== Identifier

The `+id+` property is a unique identifier
of the dataset.  A record identifier is essential for querying and identifying records within the Global Observing Facility Catalogue (GOFC).

.Example

[source,json]
----
"id": "urn:wmo:md:ca-eccc-msc:observations.swob"
----

include::../requirements/core/REQ_identifier.adoc[]

==== Conformance

The `+conformsTo+` property identifies the version of the WMDR standard to which the metadata record conforms. Conformance identification is valuable for version
detection and handling of content.

.Example

[source,json]
----
"conformsTo": [
  "http://wigos.wmo.int/spec/wmdr/2/conf/core"
]
----

include::../requirements/core/REQ_conformance.adoc[]

==== Geospatial extent

The `+geometry+` property is the location of the station/platform in the geographic coordinate system. , and provides a useful indicator of the location of the station/platform to facilitate search and map displays in the GOFC.

.Examples:

[source,json]
----
"geometry": {
  "type": "Polygon",
  "coordinates": [[
    [-142.23, 28.03],
    [-142.23, 82.56],
    [-52.16, 82.56],
    [-52.16, 28.03],
    [-142.23, 28.03]
  ]]
}
----

[source,json]
----
"geometry": {
  "type": "Point",
  "coordinates": [-79.38, 43.65]
}
----

[source,json]
----
"geometry": null
----

include::../requirements/core/REQ_extent_geospatial.adoc[]
include::../recommendations/core/REC_extent_geospatial_point.adoc[]
include::../recommendations/core/REC_extent_geospatial_precision.adoc[]
include::../recommendations/core/PER_extent_geospatial.adoc[]

===== Temporal extent

The `+time+` property describes the aggregate extent of the facility.

Temporal extents provide a useful indicator of the date and time period of the facility and facilitate temporal searching in the GOFC.

.Examples:

[source,json]
----
"time": {
  "date": "2021-10-30"
}
----

[source,json]
----
"time": {
  "timestamp": "2021-10-30T11:11:11Z"
}
----

[source,json]
----
"time": {
  "interval" : ["2020-10-30", "2021-10-30"],
  "resolution": "P1D"
}
----

[source,json]
----
"time": {
  "interval" : ["T00Z", "T23Z"],
  "resolution": "PT1H"
}
----

[source,json]
----
"time": {
  "interval": ["2018-04-22", ".."],
}
----

[source,json]
----
"time": null
----

include::../requirements/core/REQ_extent_temporal.adoc[]
include::../recommendations/core/REC_extent_temporal.adoc[]

==== Properties / Type

TODO

==== Properties / Title

TODO

==== Properties / Description

TODO

==== Properties / Contacts

The `+contacts+` property is the information associated with one or more parties responsible for the resource.

.Example: Contacts object with all contact details

[source,json]
----
"properties": {
  ...
  "contacts": [{
    "identifier": "ECCC",
    "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "name": "National Inquiry Response Team",
    "phones": [{
      "value": "+18199972800"
    }],
    "emails": [{
      "value":"enviroinfo@ec.gc.ca"
    }],
    "addresses": [{
      "deliveryPoint": [ "77 Westmorland Street, suite 260" ],
      "city": "Fredericton",
      "administrativeArea": "NB",
      "postalCode": "E3B 6Z4",
      "country": "Canada"
    }],
    "links": [{
      "href": "https://example.org/about",
      "rel": "about",
      "type": "text/html"
    }],
    "contactInstructions": "email",
    "roles": ["producer", "host"]
  }]
  ...
}
----
.Example: Contacts object with URL to the relevant homepage

[source,json]
----
"properties": {
  ...
  "contacts": [{
    "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "links": [{
      "href": "https://example.org/about",
      "rel": "about",
      "type": "text/html"
    }],
    "roles": ["producer"]
  }]
}
----

include::../requirements/core/REQ_contacts.adoc[]
include::../recommendations/core/PER_contacts.adoc[]

==== Properties / Persistent identifiers

The `+externalIds+` property is a persistent (or handle) identifier used to provide a long lasting reference to a digital resource.  Persistent identifiers are commonly used for scientific publications and datasets.

Examples of persistent identifiers include, but are not limited to:

* Digital Object Identifier (https://doi.org[DOI])
* Archival Resource Key (https://arks.org[ARK])
* https://handle.net[Handle]

.Example: Persistent identifiers

[source,json]
----
"properties": {
  ...
  "externalIds": [{
    "scheme": "https://doi.org",
    "value": "10.14287/10000001"
  }, {
    "scheme": "https://handle.net",
    "value": "2381/12775"
  }, {
    "scheme": "https://arks.org",
    "value": "ark:/13030/tf5p30086k"
  }]
  ...
}
----

.Example: Online citation

[source,json]
----
"links": [
  {
    "rel": "cite-as",
    "title": "Cite as: WMO/GAW Ozone Monitoring Community, World Meteorological Organization-Global Atmosphere Watch Programme (WMO-GAW)/World Ozone and Ultraviolet Radiation Data Centre (WOUDC) [Data]. Retrieved [YYYY-MM-DD], from https://woudc.org. A list of all contributors is available on the website. doi:10.14287/10000004",
    "type": "text/html",
    "href": "https://dx.doi.org/10.14287/10000004"
  }
]
----

include::../recommendations/core/REC_pids.adoc[]
include::../recommendations/core/PER_pids.adoc[]

==== Properties / Record creation date

The `+created+` property is a single date, being the date that the WMDR was created. Note that this date is not related to any aspect of the station/platform.

.Example:

[source,json]
----
"properties": {
  ...
  "created": "2021-06-12T23:45:24Z"
  ...
}
----

include::../requirements/core/REQ_record_creation_date.adoc[]

==== Properties / Record update date

The `+created+` property is a single date, being the date that the WMDR was created. Note that this date not related to any aspect of the station/platform.

.Example:

[source,json]
----
"properties": {
  ...
  "updated": "2022-06-12T18:52:39Z"
  ...
}
----

include::../recommendations/core/REC_record_update_date.adoc[]

==== Properties / Additional identifiers

TODO

==== Properties / Additional titles

TODO


==== Properties / Facility type

TODO

==== Properties / WMO region

TODO

==== Properties / Territories

TODO


==== Properties / Observations

TODO

==== Links and distribution information 

TODO

===== Overview

TODO

==== Additional properties

A WMDR can be extended as required for organizational purposes by adding properties (of any type) in the
record.  Additional properties do not render a record non-compliant with WMDR.

.Example:

[source,json]
----
"properties": {
  ...
  "approvalStatus": "approved"
  "_comment": {
    "validationErrors": [
      "error 1",
      "error 2"
    ]
  }
  ...
}
----

include::../recommendations/core/PER_additional_properties.adoc[]

=== WIGOS Metadata Representation resources

==== WMO Codes Registry

* http://codes.wmo.int/wmdr

==== WMO schemas server

Validation schemas, examples and other resources are published at https://schemas.wmo.int/wmdr.
