== WIGOS Metadata Representation (Version 2)

WIGOS Metadata Representation (WMDR) is an extension of the OGC API – Records standard and shall be encoded in GeoJSON. The normative provisions in WMDR (version 2) are denoted by the base URI (``http://wis.wmo.int/spec/wmdr/2``) and requirements are denoted by partial URIs relative to this base. Property names, values and examples are represented with ``shaded text`` in this document.

//:sectnums!:
=== Requirements Class "Core"

include::../requirements/requirements_class_core.adoc[]

==== Overview

The table below provides an overview of the set of properties that may be included in a WMDR.

.Table. WMDR core properties
|===
|Property|Requirement|Description

|``id``
|**Required**
|A unique identifier of the station/platform (see TODO)

|``type``
|**Required**
|A fixed value denoting the WMDR as a GeoJSON ``Feature`` (see TODO)

|``conformsTo``
|**Required**
|The version of WMDR associated to which the record conforms (see TODO)

|``geometry``
|**Required**
|Geospatial location associated with the dataset, in a geographic coordinate reference system (see TODO)

|``properties.externalIds``
|Optional
|Persistent identifiers or handles for the dataset (see TODO)

|``properties.created``
|**Required**
|The date that the WMDR was created (see TODO)

|``properties.updated``
|Optional
|The date that the WMDR was updated (see TODO)

|``properties.contacts``
|**Required**
|Contact information for the dataset (see TODO)

|===

==== WIGOS Metadata Representation representation

A WMDR can be represented in various ways internally, in WIGOS systems and software tools, but its external representation is GeoJSON.

include::../recommendations/core/REC_media_type.adoc[]

==== Validation

The WMDR schema is based on the Requirements Class "Record Core" of OGC API – Records – Part 1: Core schema and the associated information model. WMDRs compliant with the WMDR schema are therefore compliant with the OGC API – Records record schema.

include::../requirements/core/REQ_validation.adoc[]

==== Identifier

The `+id+` property is a unique identifier
of the dataset.  A record identifier is essential for querying and identifying records within the Global Discovery Catalogue (GDC).

.Example

[source,json]
----
"id": "urn:wmo:md:ca-eccc-msc:observations.swob"
----

include::../requirements/core/REQ_identifier.adoc[]

==== Conformance

The `+conformsTo+` property identifies the version of the WMDR standard to which the metadata record conforms. Conformance identification is valuable for version
detection and handling of content.

.Example

[source,json]
----
"conformsTo": [
  "http://wis.wmo.int/spec/wmdr/2/conf/core"
]
----

include::../requirements/core/REQ_conformance.adoc[]

==== Geospatial extent

The `+geometry+` property is the location of the station/platform in the geographic coordinate system. , and provides a useful indicator of the location of the station/platform to facilitate search and map displays in the GSC.

.Examples:

[source,json]
----
"geometry": {
  "type": "Polygon",
  "coordinates": [[
    [-142.23, 28.03],
    [-142.23, 82.56],
    [-52.16, 82.56],
    [-52.16, 28.03],
    [-142.23, 28.03]
  ]]
}
----

[source,json]
----
"geometry": {
  "type": "Point",
  "coordinates": [-79.38, 43.65]
}
----

[source,json]
----
"geometry": null
----

include::../requirements/core/REQ_extent_geospatial.adoc[]
include::../recommendations/core/REC_extent_geospatial_point.adoc[]
include::../recommendations/core/REC_extent_geospatial_precision.adoc[]
include::../recommendations/core/PER_extent_geospatial.adoc[]

==== Properties / Contacts

The `+contacts+` property is the information associated with one or more parties responsible for the resource.

.Example: Contacts object with all contact details

[source,json]
----
"properties": {
  ...
  "contacts": [{
    "identifier": "ECCC",
    "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "name": "National Inquiry Response Team",
    "phones": [{
      "value": "+18199972800"
    }],
    "emails": [{
      "value":"enviroinfo@ec.gc.ca"
    }],
    "addresses": [{
      "deliveryPoint": [ "77 Westmorland Street, suite 260" ],
      "city": "Fredericton",
      "administrativeArea": "NB",
      "postalCode": "E3B 6Z4",
      "country": "Canada"
    }],
    "links": [{
      "href": "https://example.org/about",
      "rel": "about",
      "type": "text/html"
    }],
    "contactInstructions": "email",
    "roles": ["producer", "host"]
  }]
  ...
}
----
.Example: Contacts object with URL to the relevant homepage

[source,json]
----
"properties": {
  ...
  "contacts": [{
    "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "links": [{
      "href": "https://example.org/about",
      "rel": "about",
      "type": "text/html"
    }],
    "roles": ["producer"]
  }]
}
----

include::../requirements/core/REQ_contacts.adoc[]
include::../recommendations/core/PER_contacts.adoc[]

==== Properties / Persistent identifiers

The `+externalIds+` property is a persistent (or handle) identifier used to provide a long lasting reference to a digital resource.  Persistent identifiers are commonly used for scientific publications and datasets.

Examples of persistent identifiers include, but are not limited to:

* Digital Object Identifier (https://doi.org[DOI])
* Archival Resource Key (https://arks.org[ARK])
* https://handle.net[Handle]

.Example: Persistent identifiers

[source,json]
----
"properties": {
  ...
  "externalIds": [{
    "scheme": "https://doi.org",
    "value": "10.14287/10000001"
  }, {
    "scheme": "https://handle.net",
    "value": "2381/12775"
  }, {
    "scheme": "https://arks.org",
    "value": "ark:/13030/tf5p30086k"
  }]
  ...
}
----

.Example: Online citation

[source,json]
----
"links": [
  {
    "rel": "cite-as",
    "title": "Cite as: WMO/GAW Ozone Monitoring Community, World Meteorological Organization-Global Atmosphere Watch Programme (WMO-GAW)/World Ozone and Ultraviolet Radiation Data Centre (WOUDC) [Data]. Retrieved [YYYY-MM-DD], from https://woudc.org. A list of all contributors is available on the website. doi:10.14287/10000004",
    "type": "text/html",
    "href": "https://dx.doi.org/10.14287/10000004"
  }
]
----

include::../recommendations/core/REC_pids.adoc[]
include::../recommendations/core/PER_pids.adoc[]

==== Properties / Record creation date

The `+created+` property is a single date, being the date that the WMDR was created. Note that this date is not related to any aspect of the station/platform.

.Example:

[source,json]
----
"properties": {
  ...
  "created": "2021-06-12T23:45:24Z"
  ...
}
----

include::../requirements/core/REQ_record_creation_date.adoc[]

==== Properties / Record update date

The `+created+` property is a single date, being the date that the WMDR was created. Note that this date not related to any aspect of the station/platform.

.Example:

[source,json]
----
"properties": {
  ...
  "updated": "2022-06-12T18:52:39Z"
  ...
}
----

include::../recommendations/core/REC_record_update_date.adoc[]

==== Properties / WMO data policy

The `+wmo:dataPolicy+` property is a codelist that identifies the classification of the dataset exchange as described by the WMO Unified Data Policy (Resolution 1 (Cg-Ext(2021)))footnote:[Resolution 1 (Cg-Ext(2021)) – WMO Unified Policy for the International Exchange of Earth System Data (World Meteorological Congress: Abridged Final Report of the Extraordinary Session (WMO-No. 1281))] for the international exchange of Earth system data. The code list values are `+core+` or `+recommended+`.  The `+wmo:dataPolicy+` property is required if the metadata record describes a dataset.

Licensing and copyright are expressed via the `+links+` property (see TODO), providing access, license and attribution details as required. Conditions on use of the data should be indicated for transparency and clarification.

.Example: Core data

[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "core"
  ...
}
----

.Example: Recommended data
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
}
----

It is useful to add provider-specific details to have the most detailed information about data policy and additional conditions.

.Example: Recommended data with additional conditions and provider-specific details
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
},
"links": [{
  "rel": "license",
  "href": "https://example.org/license",
  "type": "text/html",
  "title": "EUMETSAT DATA LICENSING"
}]
----

.Example: License for recommended data in the public domain
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
},
"links": [{
  "rel": "license",
  "href": "https://creativecommons.org/publicdomain/zero/1.0/",
  "type": "text/html",
  "title": "CC0 1.0 Deed | CC0 1.0 Universal | Creative Commons"
}]
----

To express rights not addressed by a license, the `+rights+` property can be used as follows:

.Example: Rights
[source,json]
----
"properties": {
 ...
 "rights": "Users are granted free and unrestricted access to this data, without charge and with no conditions on use. Users are requested to attribute the producer of this data. WMO Unified Data Policy (Resolution 1 (Cg-Ext 2021))."
 ...
}
----

include::../requirements/core/REQ_data_policy.adoc[]
include::../recommendations/core/REC_data_policy.adoc[]
include::../recommendations/core/PER_data_policy.adoc[]

==== Links and distribution information 

TODO

===== Overview

TODO

==== Additional properties

A WMDR can be extended as required for organizational purposes by adding properties (of any type) in the
record.  Additional properties do not render a record non-compliant with WMDR.

.Example:

[source,json]
----
"properties": {
  ...
  "approvalStatus": "approved"
  "_comment": {
    "validationErrors": [
      "error 1",
      "error 2"
    ]
  }
  ...
}
----

include::../recommendations/core/PER_additional_properties.adoc[]

=== WMO Core Metadata Profile resources

==== WMO Codes Registry

* http://codes.wmo.int/wmdr

==== WMO schemas server

Validation schemas, examples and other resources are published at https://schemas.wmo.int/wmdr.
