---
type: object
properties:
  id:
    type:
      - string
      - integer
    description: instrument identifier
  geometry:
    $ref: 'https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/pointGeoJSON.yaml'
  observedGeometry:
    $ref: 'https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/theme.yaml#/properties/concepts/items'
    description: observed geometry
    $comment: |-
      - https://codes.wmo.int/wmdr/Geometry
  time:
    $ref: 'https://raw.githubusercontent.com/wmo-im/wcmp2/refs/heads/main/schemas/wcmpRecordGeoJSON.yaml#/properties/time'
  observingMethod:
    $ref: 'https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/theme.yaml#/properties/concepts/items'
    description: observing method
    $comment: |-
      - https://codes.wmo.int/wmdr/ObservingMethodAtmosphere
      - https://codes.wmo.int/wmdr/ObservingMethodTerrestrial
      - https://codes.wmo.int/wmdr/ObservingMethodEarth
  operatingStatus:
    $ref: 'https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/theme.yaml#/properties/concepts/items'
    description: operating status
    $comment: |-
      - https://codes.wmo.int/wmdr/InstrumentOperatingStatus
  sourceOfObservation:
    $ref: 'https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/theme.yaml#/properties/concepts/items'
    description: Source of observation
    $comment: https://codes.wmo.int/wmdr/SourceOfObservation
  instrument:
    oneOf:
      - type: object
        properties:
          id:
            type:
              - string
              - integer
        required:
          - id
      - $ref: 'instrument.yaml'
  instrumentSerialNumber:
    type: string
    description: instrument serial number
  referenceSurface:
    $ref: 'https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/theme.yaml#/properties/concepts/items'
    description: Type of reference surface
    $comment: https://codes.wmo.int/wmdr/ReferenceSurfaceType
  verticalDistances:
    type: object
    properties:
        value:
          type: number
          description: Height above reference surface
        unit:
          $ref: 'https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/theme.yaml#/properties/concepts/items'
          description: Measurement unit
          $comment: https://codes.wmo.int/wmdr/unit
required:
  - id
  - time
