---
type: object
required:
  - id
properties:
  id:
    oneOf:
      - type: string
      - type: integer
    description: deployment identifier
  geometry:
    $ref: 'https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/pointGeoJSON.yaml'
  time:
    $ref: 'https://raw.githubusercontent.com/wmo-im/wcmp2/refs/heads/main/schemas/wcmpRecordGeoJSON.yaml#/properties/time'
  instrument:
    type: string
    description: instrument identifier
  sourceOfObservation:
    type: string
    description: Source of observation
    $comment: https://codes.wmo.int/wmdr/SourceOfObservation
  referenceSurface:
    type: string
    description: Type of reference surface
    $comment: https://codes.wmo.int/wmdr/ReferenceSurfaceType
  keywords:
    $ref: 'https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordCommonProperties.yaml#/properties/keywords'
