---
type: object
properties:
  id:
    type:
      - string
      - integer
    description: instrument identifier
  geometry:
    $ref: 'https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/pointGeoJSON.yaml'
  time:
    $ref: 'https://raw.githubusercontent.com/wmo-im/wcmp2/refs/heads/main/schemas/wcmpRecordGeoJSON.yaml#/properties/time'
  keywords:
    $ref: 'https://schemas.opengis.net/ogcapi/records/part1/1.0/openapi/schemas/recordCommonProperties.yaml#/properties/keywords'
  instrument:
    oneOf:
      - type: object
        properties:
          id:
            type:
              - string
              - integer
        required:
          - id
      - $ref: 'instrument.yaml'
  referenceSurfaces:
    type: array
    minItems: 1
    items:
      type: object
      properties:
        referenceSurface:
          type: string
          description: Type of reference surface
          $comment: https://codes.wmo.int/wmdr/ReferenceSurfaceType
        verticalDistance:
          type: number
          description: Height above reference surface
      required:
        - referenceSurface
        - verticalDistance
required:
  - id
  - instrument
